SELECT TOP (1000) [student_id]
      ,[student_name]
      ,[grade]
      ,[mathematics_mark]
      ,[physical_science_mark]
      ,[life_sciences_mark]
      ,[english_home_language_mark]
      ,[life_orientation_mark]
      ,[information_technology_mark]
      ,[agricultural_science_mark]
      ,[total_mark]
      ,[average_mark]
  FROM [staging].[bronze].[prelim_science_students_marks]
